MOVIEBOOKIE/MOVIEBOOKIE_FE

- src/app/(fullscreen)/intro/page.tsx
어떤 변경 사항이 있나요?
close #39
- 빌드오류난 경로 수정하였습니당
---
---
> [Bug/#39 ] 배포 빌드 오류 

- src/app/(tabs)/home/page.tsx
- src/app/page.tsx
어떤 변경 사항이 있나요?
close #41 
- home폴더 만들었습ㄴ다. 
- netlify 코드는 스프린트 이후에 삭제할게요
---
---
> [Bug/#41] 배포 404 에러

- src/app/(fullscreen)/trait-result/content.tsx
- src/app/(fullscreen)/trait-result/page.tsx
어떤 변경 사항이 있나요?
close #
- 
---
---
> [Bug/#] trait-result build error

- src/app/_utils/api.ts
어떤 변경 사항이 있나요?
close #
- 
---
---
> [Bug/#]카카오 로그인 빌드에러

- src/app/_utils/api.ts
어떤 변경 사항이 있나요?
close #
- 
---
---
> [Bug/#]카카오 로그인 BaseUrl 수정

- .github/workflows/deploy.yml
- build.sh
- src/app/(fullscreen)/event/ticket/_components/card-front.tsx
어떤 변경 사항이 있나요?
close #88 
- 자동 배포 설정
---
---
> [Setting/#88] 자동 배포 설정

- src/app/_components/detail-content.tsx
어떤 변경 사항이 있나요?
close #111 
- 배포 빌드 오류 해결
---
배포 빌드 오류 해결
---
> [Bug/#111] 배포 빌드 오류 해결

- src/app/(fullscreen)/event/success/page.tsx
어떤 변경 사항이 있나요?
close #
- 빌드 오류 해결
---
---
> [Bug] 빌드 오류 해결

- src/app/(fullscreen)/event/success/_components/step1.tsx
- src/app/_components/detail-content.tsx
어떤 변경 사항이 있나요?
close #
- 
---
---
> [fix/build] 클라이언트에서만 실행되도록 빌드오류 수정

- src/app/(fullscreen)/event/success/_components/client-wrapper.tsx
- src/app/(fullscreen)/event/success/_components/client.tsx
- src/app/(fullscreen)/event/success/_components/step1.tsx
- src/app/(fullscreen)/event/success/_components/step2.tsx
- src/app/(fullscreen)/event/success/page.tsx
어떤 변경 사항이 있나요?
close #
- 
---
---
> [Bug] 배포 오류 수정

- src/app/(fullscreen)/event-create/components/post-textarea.tsx
- src/app/(fullscreen)/event-create/page.tsx
- src/app/(tabs)/home/page.tsx
- src/app/_components/detail-content.tsx
- src/app/_components/pwa-prompt-modal.tsx
- src/app/_stores/useEventCreateForm.ts
- src/app/_styles/globals.css
- src/app/_types/event.ts
- src/app/_utils/create-event-formdata.ts
- src/lib/auth/sendAuthCodeToServer.ts
어떤 변경 사항이 있나요?
close #
- 
---
---
> feat: 빌드오류 해결, 카카오로그인 axios 수정

- package.json
- pnpm-lock.yaml
- src/app/(fullscreen)/event-create/components/post-textarea.tsx
- src/app/(fullscreen)/event-create/page.tsx
- src/app/(tabs)/home/page.tsx
- src/app/_components/detail-content.tsx
- src/app/_components/pwa-prompt-modal.tsx
- src/app/_stores/useEventCreateForm.ts
- src/app/_styles/globals.css
- src/app/_types/event.ts
- src/app/_utils/create-event-formdata.ts
- src/lib/auth/sendAuthCodeToServer.ts
어떤 변경 사항이 있나요?
close #
- 
---
---
> [Feature/96] 모듈 설치, 빌드오류 

- src/app/(fullscreen)/event/success/_components/client.tsx
- src/app/(fullscreen)/event/success/_components/step1.tsx
- src/app/(tabs)/event/_components/event-tabs.tsx
- src/app/(tabs)/event/page.tsx
- src/app/_hooks/use-create-event.ts
어떤 변경 사항이 있나요?
close #
- 
---
---
> feat: qa 반영, success api 요청

- src/app/(fullscreen)/event/success/_components/client.tsx
- src/app/(fullscreen)/layout.tsx
- src/app/(tabs)/home/page.tsx
- src/app/(tabs)/layout.tsx
- src/app/_hooks/use-create-event.ts
- src/app/_styles/globals.css
어떤 변경 사항이 있나요?
close #
- 
---
---
> fix: 타이포 수정, 스크롤 제거,useCreateEvent

- src/app/(fullscreen)/event-create/components/step5-people.tsx
- src/app/(fullscreen)/event-create/page.tsx
- src/app/(fullscreen)/login/kakao/page.tsx
- src/app/(fullscreen)/set-profile/page.tsx
- src/app/(fullscreen)/verify/email/page.tsx
- src/app/(fullscreen)/verify/phone/page.tsx
- src/app/(fullscreen)/verify/verify-number/page.tsx
- src/app/_constants/paths.ts
- src/app/_hooks/onboarding/useKakaoLogin.ts
- src/app/_hooks/onboarding/useSendCode.ts
- src/app/_hooks/onboarding/useVerifyCode.ts
어떤 변경 사항이 있나요?
close #
- 
---
---
> [Feature/101-2] 사용자인증 api, 인원제한, 캘린더 토스트 추가

- src/app/(fullscreen)/agreement/page.tsx
- src/app/(fullscreen)/login/kakao/page.tsx
- src/app/_constants/paths.ts
어떤 변경 사항이 있나요?
close #136 
-  카카오로그인 후 정보동의 페이지로 가게해서 온보딩 플로우 연결완료하였습니다 
---
---
> [Feature/#136] 온보딩플로우 연결

- src/app/(fullscreen)/event-completed/page.tsx
- src/app/(fullscreen)/feedback/page.tsx
- src/app/(fullscreen)/feedback/result/page.tsx
- src/app/(tabs)/my-page/page.tsx
- src/app/_apis/auth/mypage.ts
- src/app/_apis/methods.ts
- src/app/_apis/type.ts
- src/app/_hooks/auth/use-mypage.tsx
어떤 변경 사항이 있나요?
close #138 
---
-  피드백 코드에 포함시켰던 상영완료 페이지가 피드백 플로우가 아니라 , 알림눌렀을때 뜨는 페이지라서 따로 구분했고, 
-  마이페이지 api 연결했는데 백엔드 수정할 부분 있어서 추후 확인해야합니다 .
---
> [Feature/#138] 마이페이지 API 연결, 피드백 퍼블리싱 수정

- src/middleware.ts
어떤 변경 사항이 있나요?
---
- 제가 작업하다가 실수로 지워버려서 ㅎㅎㅎ..... 다시 그대로 추가했습니다...
---
> feat:add 초기 진입 로직 추가 middleware 재추가

- public/custom-sw/sw.js
- public/firebase-config.js
- src/app/_apis/noti.ts
- src/app/_components/fcm/debug-logger.tsx
- src/app/_components/fcm/fcm-listener.tsx
- src/app/_utils/dev-logger.ts
- src/app/layout.tsx
- src/app/lib/firebase-notification.ts
어떤 변경 사항이 있나요?
---
- 제발 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
> [Feature/#212] fcm 토스트 알림 테스트

- src/app/(tabs)/home/_components/carousel.tsx
- src/app/(tabs)/home/page.tsx
- src/app/_components/badge.tsx
- src/app/_components/fixed-layout.tsx
- src/app/_components/input.tsx
- src/app/_components/main-card.tsx
- src/app/layout.tsx
어떤 변경 사항이 있나요?
close #215 
- 디자인 QA 수정 1차
---
디자인 QA 수정 1차
---
> [Design/#215] 디자인 QA 수정 1차

- src/app/(tabs)/home/page.tsx
어떤 변경 사항이 있나요?
close #
---
---
> [fix/noti] 모든 환경에서 fcm 토큰 등록하도록

- src/app/(fullscreen)/detail/[id]/page.tsx
- src/app/(fullscreen)/detail/_components/information-tab.tsx
- src/app/_components/button.tsx
- src/app/_components/detail-content.tsx
어떤 변경 사항이 있나요?
close #258 
---
- 디테일 페이지 디자인 수정
- 버튼 스타일 추가
---
> [Design/#258] 디테일 페이지 디자인 수정

- src/app/(fullscreen)/event-create/_components/cinema-skeleton-card.tsx
- src/app/(fullscreen)/event-create/components/step6-place.tsx
- src/app/(tabs)/event/_components/ticket-skeleton-card.tsx
- src/app/(tabs)/event/_components/ticket-tab.tsx
어떤 변경 사항이 있나요?
close #272 
---
리스트 UI 스켈레톤 처리
---
https://github.com/user-attachments/assets/9fef4d86-0351-4e8f-8ea1-1e6feb4f010e
> [Feature/#272] 리스트 UI 스켈레톤 처리

- src/app/_apis/register-fcm-token.ts
- src/app/_context/loading-context.tsx
- src/app/_context/toast-context.tsx
어떤 변경 사항이 있나요?
close #293 
---
---
> [Bug/#293] 에러 페이지 수정

- src/app/(fullscreen)/detail/[id]/page.tsx
- src/app/(fullscreen)/trait/result/page.tsx
- src/app/_context/loading-context.tsx
어떤 변경 사항이 있나요?
close #273 
---
- 유형결과 뒤로가기 
- 빌드오류
---
> [Bug/#273] 빌드오류 해결

- src/app/(fullscreen)/detail/[id]/page.tsx
- src/app/(fullscreen)/trait/result/page.tsx
- src/app/_components/noti-toast.tsx
- src/app/_context/loading-context.tsx
- src/app/_context/toast-context.tsx
- src/app/_hooks/fcm/use-fcm.ts
어떤 변경 사항이 있나요?
close #
---
---
> [Bug/273] 에러페이지 관련 알림 토큰 등록 코드 수정

- src/app/_hooks/fcm/use-fcm-handler.ts
- src/app/_hooks/fcm/use-fcm.ts
어떤 변경 사항이 있나요?
close #300 
---
기타 오류 수정
---
> [Bug/#300] 기타 오류 수정

- .github/workflows/git-push.yml
- next.config.ts
어떤 변경 사항이 있나요?
close #
---
- dev 브랜치는 버셀에서 개발용으로 배포되고 
- main 브랜치는 운영용 서버로 배포됩니다. 
- 워크플로우로 dev 브랜치에 푸시해서 머지되면 자동 개발용 서버로 버셀 preview 배포되고, 
- main 브랜치는 운영용 서버로 production 배포됩ㄴ디ㅏ
> [Feat/deploy] dev/main 브랜치별 버셀 자동 배포

- src/app/(fullscreen)/login/kakao/page.tsx
- src/app/(tabs)/home/page.tsx
- src/app/_hooks/onboarding/use-kakao-login.ts
- src/app/_hooks/use-small-screen.ts
- src/middleware.ts
어떤 변경 사항이 있나요?
close #326
---
- 모바일에서 카카오리다이렉트 오류 로그 확인해보기 위해 추가
- 홈 포스터위치 수정 
---
> [fix/#326] 리다이렉트오류 로그 추가

- src/app/layout.tsx
어떤 변경 사항이 있나요?
close #328 
---
노치를 위한 메타태그 추가
---
> [Design/#328] 노치를 위한 메타태그 추가

- src/app/(fullscreen)/detail/_components/top-bar.tsx
- src/app/_components/detail-content.tsx
- src/app/_components/header.tsx
- src/app/_styles/base.css
- src/app/_styles/utilities.css
어떤 변경 사항이 있나요?
close #333 
---
뒤로가기 위치 수정 및 디테일 페이지 디자인 수정
---
> [Design/#333] 뒤로가기 위치 수정 및 디테일 페이지 디자인 수정

- README.md
- jest.config.js
- jest.setup.ts
- next.config.ts
- package.json
- pnpm-lock.yaml
- src/__mocks__/next/navigation.ts
- src/app/(fullscreen)/event-create/components/period-calendar.tsx
- src/app/(tabs)/home/_components/carousel.tsx
- src/app/(tabs)/my-page/__tests__/page.test.tsx
- src/app/_components/button.test.tsx
- src/app/_utils/__tests__/deadline-utils.test.ts
- src/app/_utils/deadline-utils.ts
- vercel.json
어떤 변경 사항이 있나요?
close #322
---
- 아ㅏㅏ...이 테스트코드는 잘돌아가는지 확인해봐야ㅛ해서..글고 초반 이해가 좀 필요해서 주석처리 이해 부탁드립니다 ㅎㅎㅎ...
- 익숙해지면 지울게요..ㅎㅎㅎ 
- 마이페이지는 RTL로 렌더링 테스트햇고, 날짜계산 유틸 분리해서, jest로 유닛테스트햇습니다 
- 캐러셀 round 수정 
---
> [Test/#322] 테스트환경세팅, 마이페이지/유틸 초기테스트, 캐러셀 수정

- src/app/(fullscreen)/detail/_components/top-bar.tsx
- src/app/(fullscreen)/search/page.tsx
- src/app/(fullscreen)/trait/result/page.tsx
- src/app/(tabs)/home/_components/empty-carousel.tsx
- src/app/_components/header.tsx
어떤 변경 사항이 있나요?
close #
---
---
> [fix/#347] 노치대응 헤더영역 수정

- next.config.ts
- src/app/(fullscreen)/detail/_components/map-thumbnail.tsx
- src/app/api/naver-map/route.ts
어떤 변경 사항이 있나요?
close #344 
---
지도 네이버로 변경 및 연결
---
> [Refactor/#344] 지도 네이버로 변경 및 연결

- src/app/(fullscreen)/verify/email/page.tsx
- src/app/(fullscreen)/verify/phone/page.tsx
- src/app/(fullscreen)/verify/verify-number/page.tsx
- src/app/(tabs)/my-page/page.tsx
- src/app/_components/fixed-layout.tsx
- src/app/_components/header.tsx
- src/app/_styles/base.css
어떤 변경 사항이 있나요?
close #355
---
- 마이페이지 정보 인증한 이메일로 정보수정
- 인증로직에서도 버튼에 로딩 스피너 추가 
- 오류시 alert -> toast 변경
---
> [Bug/#355] 인증이메일 수정, 인증로직 로딩스피너 추가

- src/app/(fullscreen)/event/success/_components/step1.tsx
- src/app/(fullscreen)/trait/_components/motion.ts
- src/app/(fullscreen)/trait/result/page.tsx
- src/app/(tabs)/home/_components/carousel.tsx
- src/app/(tabs)/home/page.tsx
- src/app/_components/complete.tsx
- src/app/_components/detail-content.tsx
- src/app/_components/modal.tsx
- src/app/_components/type-list.tsx
- src/app/_utils/text-motion.ts
어떤 변경 사항이 있나요?
close #357
---
- 생성로직 중 미리보기-> 게시 -> 완료페이지 모션 추가 
-  유형 결과 페이지 모션추가 
- 캐러셀 오른쪽 포스터 안보이는 문제해결
- 캐러셀 포스터 추천 랜덤으로 보여지도록
---
https://github.com/user-attachments/assets/597f3a0e-df87-4fc3-9689-8677e6c97d29
https://github.com/user-attachments/assets/c46d2a8d-9554-44eb-a4b3-4da869115ca1
https://github.com/user-attachments/assets/a5a99315-2646-485f-b30c-7f75906e652f
> [Bug/#357] 캐러셀 스크롤 수정, motion 추가
